CodeFusion Studio 1.1.0
Features:

- System Planner: A new centralized interface for accessing
  configuration tools and managing workspace resources, including cores,
  peripherals, clocks, pins, and memory partitions.
- Memory Allocation: Define and manage memory partitions per core to
  optimize resource distribution across multi-core SoCs.
- Peripheral Allocation: Assign and configure peripheral blocks per core
  directly within the System Planner.
- Heterogeneous Multi-Core Debugging: Debug multiple cores in a single
  environment, eliminating the need for multiple IDEs.
- Device Tree View: Enables hardware component review for Zephyr-based
  projects, improving visibility and configuration management.
- Workspaces for Multi-Core Projects: Projects are now upgraded to
  workspaces, allowing one project per core for better organization and
  management. This ensures a streamlined development process across
  multiple cores in a unified workspace.
- UX upgrades: Improved accessibility and usability for the Registers
  page and Pin Config page.
- Context menu enhancements: With the move to multi-project per core
  workspaces, context-based action filtering has been introduced.
  Clicking on a project in the Context panel dynamically updates the
  Actions panel to display only relevant actions.
- Catalog Manager: A background service that automatically syncs the SoC
  data model, ensuring up-to-date information on cores, boards, and
  other hardware configurations.
- Plugin-based project creation: A flexible, extensible plugin
  architecture that cleanly separates configuration from code
  generation, allowing developers to create plugins that align with
  internal standards.

Signed-off-by: Mike Harrington <michael.harrington@analog.com>

diff --git a/packages/ide/Dockerfile.test b/packages/ide/Dockerfile.test
--- a/packages/ide/Dockerfile.test
+++ b/packages/ide/Dockerfile.test
@@ -34,6 +34,7 @@ RUN apt-get update && apt-get install --no-install-recommends -y \
   libxcb-icccm4 \
   libxcb-image0 \
   libxcb-keysyms1 \
+  unzip \
   libxcb-randr0 \
   libxcb-render-util0 \
   libxcb-shape0 \
@@ -45,6 +46,11 @@ RUN apt-get update && apt-get install --no-install-recommends -y \
   rm -rf /var/lib/apt/lists/*
 
 RUN update-ca-certificates
+
+RUN curl -O https://artifactory.analog.com:443/artifactory/dte-kits/CFSIO-00/1.1.0/w2501037/CodeFusionStudio_1.1.0.run && \
+    chmod +x CodeFusionStudio_1.1.0.run && \
+    ./CodeFusionStudio_1.1.0.run --root /github/home/analog/cfs/1.1.0 --accept-licenses --default-answer --confirm-command install || echo "Installation failed" && \
+    rm CodeFusionStudio_1.1.0.run
 
 # Install NVM, NodeJS, yarn, vsce
 ENV NVM_DIR=/.nvm
